### ISSUE TITLE
Fail to install PyQt6-tools

### ISSUE THREAD

**Issue by Bennett1972** [altendky/pyqt-tools#103]
I try to several times to install PyQt6-tools on my Mac M1 machine. Please let me know if you know the answer.
Here is my information.
Python version: 3.8.9
PyQt6 version: 6.2.3

Here is the error message.

40:353: execution error:     ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxjdjnscn
         cwd: /private/tmp/pip-install-mlfjakgd/pyqt6
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 594, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 60, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 241, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/tmp/pip-build-env-pnji587r/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpxjdjnscn Check the logs for full command output.

**Comment by Bennett1972** [comment]
Any suggestion for this? I tried several versions but all failed.

**Comment by TheGiolly** [comment]
Have you tried updating pip?
`pip install --upgrade pip`

**Comment by Bennett1972** [comment]
> Have you tried updating pip? `pip install --upgrade pip`

Yes. But it still fails.

**Comment by wesgm** [comment]
I'm having the same error right now, here is the output. my venv is using python 3.9
`Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.1.0
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/wesley/python-environs/ccf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/wesley/python-environs/ccf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/wesley/python-environs/ccf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/wesley/python-environs/ccf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/zj/jpgvrn1s4yb3zk2dnbhcpd8c0000gn/T/pip-build-env-e8unpp0k/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by pwyngaard** [comment]
Me too, almost identical error as @wesgm, python 3.9.16 in venv, mac m1:

```
Collecting pyqt6-tools
  Downloading pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting pyqt6==6.1.0
  Downloading PyQt6-6.1.0.tar.gz (946 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 946.9/946.9 kB 4.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/peterw/projects/ib/spike01/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/peterw/projects/ib/spike01/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/peterw/projects/ib/spike01/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/2l/cccf_56n6c371mhxl6tqj91r0000gn/T/pip-build-env-8q9f_kl_/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by qiemanqieman** [comment]
I encountered this error with python3.10 on windows:

`pip3 install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
  Using cached pyqt6_tools-6.0.3.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.0.3
  Downloading PyQt6-6.0.3.tar.gz (941 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 941.4/941.4 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
ERROR: Exception:
Traceback (most recent call last):
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\distributions\sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\req\req_install.py", line 539, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\operations\build\metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\utils\misc.py", line 722, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\utils\subprocess.py", line 252, in runner
    call_subprocess(
  File "C:\ProgramFiles\Python310\lib\site-packages\pip\_internal\utils\subprocess.py", line 166, in call_subprocess
    line: str = proc.stdout.readline()
MemoryError
`

**Comment by monkeychen** [comment]
Me too, almost identical error as @wesgm, python 3.9.6 in venv, mac m1:
-> % pip install pyqt6-tools
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pyqt6-tools
  Using cached https://mirrors.aliyun.com/pypi/packages/d0/5a/125c5c43772d4d94554e9c31ccca9645c5e69f1c7aba4e43d5b427dc4d42/pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.1.0
  Using cached https://mirrors.aliyun.com/pypi/packages/64/be/d2b48e53d5767f25d607fa5a598e2af6ef9e1e8475bd6bfc60b27a5f34ea/PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/chenzhian/env/venv-py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/chenzhian/env/venv-py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/chenzhian/env/venv-py39/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/1y/_n58xgp93rxflwp5117pwyrh0000gn/T/pip-build-env-vrjty0fp/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by altendky** [comment]
I'm trying to get an updated release...  https://github.com/altendky/pyqt-tools/issues/110

**Comment by altendky** [comment]
Also, if you don't need the plugins and just want the Qt applications, consider the `qt5-tools` and `qt6-tools` packages that aren't dependent on PyQt and are also not specific to any Python 3 version.  Though yes, even those are behind and not providing the latest Qt application versions.

**Comment by wangchunlei000** [comment]
So,what is the solution? I need help !

**Comment by altendky** [comment]
Most services don't provide macOS M1/ARM runners presently so it is harder to provide wheels for that.  The best path forward for you depends on what specifically you need this for.  As noted, the `qt-applications` and `qt-tools` packages are not specific to any given Python version and the applications are provided as Universal2 so they should work on M1 etc ARM systems.

If you say more about your specific situation then I can perhaps provide a more specific response.

**Comment by FabioPlunser** [comment]
Also having the same problem just can't install pyqt6-tools on Apple Silicon. 

I installed pyqt6 just fine and the app runs but i can't install the tools to update the ui. 
Is there a fix yet?
```bash
❯ pip3 install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.4.2.3.3-py3-none-any.whl (29 kB)
Collecting click (from pyqt6-tools)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pyqt6==6.4.2 (from pyqt6-tools)
  Using cached PyQt6-6.4.2-cp37-abi3-macosx_10_14_universal2.whl (11.6 MB)
INFO: pip is looking at multiple versions of pyqt6-tools to determine which version is compatible with other requirements. This could take a while.
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.3.1.3.3-py3-none-any.whl (29 kB)
Collecting pyqt6==6.3.1 (from pyqt6-tools)
  Using cached PyQt6-6.3.1-cp37-abi3-macosx_10_14_universal2.whl (11.7 MB)
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/04/wy0mjdy16jq6n9923dlpv7vw0000gn/T/pip-build-env-8_yv3vnr/overlay/lib/python3.12/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/04/wy0mjdy16jq6n9923dlpv7vw0000gn/T/pip-build-env-8_yv3vnr/overlay/lib/python3.12/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/04/wy0mjdy16jq6n9923dlpv7vw0000gn/T/pip-build-env-8_yv3vnr/overlay/lib/python3.12/site-packages/sipbuild/project.py", line 602, in setup
          self.update(tool)
        File "/private/var/folders/04/wy0mjdy16jq6n9923dlpv7vw0000gn/T/pip-install-8049xod3/pyqt6_83cb9a4fb2414193b3ceb57c7be399cb/project.py", line 157, in update
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bigbigtooth** [comment]
I have same problem, any solutions ???

run : pip install pyqt6-tools on Macbook pro M3Max
Error print:
  Installing collected packages: tomli, setuptools, packaging, sip, PyQt-builder
  Successfully installed PyQt-builder-1.15.4 packaging-23.2 setuptools-69.0.3 sip-6.8.1 tomli-2.0.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Querying qmake about your Qt installation...
  pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
  Traceback (most recent call last):
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/davidwu/anaconda3/envs/LiveroomAssistant/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-4bxfao59/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
      project = AbstractProject.bootstrap('wheel',
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-4bxfao59/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
      project.setup(pyproject, tool, tool_description)
    File "/private/var/folders/vs/t8pyxcvj5mxfpvqsk7j0kf8h0000gn/T/pip-build-env-4bxfao59/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 603, in setup
      self.update(tool)
    File "project.py", line 157, in update
  sipbuild.exceptions.UserException
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

**Comment by EasyCommanderZ** [comment]
I got the same problem and it seems that pyqt-tools does not support Mac with M series CPU

**Comment by FabioPlunser** [comment]
I solved it by copying the terminal application activating rossetta mode and installing it via rosetta.

**Comment by StephenDeng01** [comment]
> I solved it by copying the terminal application activating rossetta mode and installing it via rosetta.

Execuse me, could you please give me some more information in your way?

**Comment by altendky** [comment]
in case you have the time to help out, fyi: https://github.com/altendky/pyqt-tools/issues/132
