### ISSUE TITLE
Any chance on 3.12 update soon?

### ISSUE THREAD

**Issue by Gh0sTG0** [altendky/pyqt-tools#120]
Hi. Trying to install this on 3.12.1 latest, pip-setuptools-wheel are updated to latest. Having error:
```
(.venv) PS D:\PyProjects\test1> pip install -U pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.4.2.3.3-py3-none-any.whl (29 kB)
Collecting click (from pyqt6-tools)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pyqt6==6.4.2 (from pyqt6-tools)
  Using cached PyQt6-6.4.2-cp37-abi3-win_amd64.whl (6.4 MB)
INFO: pip is looking at multiple versions of pyqt6-tools to determine which version is compatible with other requirements. This could take a while.
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.3.1.3.3-py3-none-any.whl (29 kB)
Collecting pyqt6==6.3.1 (from pyqt6-tools)
  Using cached PyQt6-6.3.1-cp37-abi3-win_amd64.whl (6.3 MB)
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl (29 kB)
Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "D:\PyProjects\test1\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\PyProjects\test1\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\PyProjects\test1\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\sipbuild\project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\ghost\AppData\Local\Temp\pip-install-okx6tnki\pyqt6_3aa250aa442149ccafa78c508e672927\project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\ghost\AppData\Local\Temp\pip-build-env-ckquya1p\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any chance on 3.12 update?

**Comment by SharryXu** [comment]
I've met the same issue. Do we have any plans to support python 3.12 recently? @altendky

**Comment by carverrn1** [comment]
Same issue.  Python 3.12. Windows 10 Pro.

Update: I've switched to Python 3.10.11 as a work-around.

**Comment by Richemond-Gbekley** [comment]
The same issue. how do i go about it ?

**Comment by Marigem** [comment]
Same issue here, Hopefully it gets updated for latest python versions at some point.

**Comment by Stratia** [comment]
Issue still occuring.

**Comment by ZeldaJC** [comment]
Same Error:

PS D:\Users\Admin> pip install PyQt5-tools
Collecting PyQt5-tools
  Using cached pyqt5_tools-5.15.9.3.3-py3-none-any.whl.metadata (8.3 kB)
Collecting click (from PyQt5-tools)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pyqt5==5.15.9 (from PyQt5-tools)
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
INFO: pip is looking at multiple versions of pyqt5-tools to determine which version is compatible with other requirements. This could take a while.
Collecting PyQt5-tools
  Using cached pyqt5_tools-5.15.4.3.2-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt5==5.15.4 (from PyQt5-tools)
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "C:\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\sipbuild\api.py", line 28, in build_wheel     
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\sipbuild\project.py", line 602, in setup      
          self.apply_user_defaults(tool)
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-install-3lkw366g\pyqt5_d2d2e206762b413b837f57ef0e10fb0e\project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\pyqtbuild\project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "D:\Users\AdminTCT\AppData\Local\Temp\pip-build-env-0eq9opsr\overlay\Lib\site-packages\pyqtbuild\builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ZeldaJC** [comment]
Same error, can not fix it!

**Comment by Stratia** [comment]
I got around this issue by installing this instead, as I needed to use Qt-designer.

https://build-system.fman.io/qt-designer-download

**Comment by altendky** [comment]
in case you have the time to help out, fyi: https://github.com/altendky/pyqt-tools/issues/132
