### ISSUE TITLE
Unable to install pyqt6-tools

### ISSUE THREAD

**Issue by Akash47007** [altendky/pyqt-tools#124]
Hello, When i used pip to install pyqt6-tools i get this error,

Collecting pyqt6-tools
  Using cached pyqt6_tools-6.4.2.3.3-py3-none-any.whl.metadata (8.3 kB)
Collecting click (from pyqt6-tools)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting pyqt6==6.4.2 (from pyqt6-tools)
  Using cached PyQt6-6.4.2-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
INFO: pip is looking at multiple versions of pyqt6-tools to determine which version is compatible with other requirements. This could take a while.
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.3.1.3.3-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt6==6.3.1 (from pyqt6-tools)
  Using cached PyQt6-6.3.1-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Akash\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 92, in bootstrap       
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\sipbuild\project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\Akash\AppData\Local\Temp\pip-install-c5a1zs5c\pyqt6_70cad25edec84e2f9db16d54eabb31ed\project.py", line 60, in apply_user_defaults    
          super().apply_user_defaults(tool)
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\pyqtbuild\project.py", line 51, in apply_user_defaults     
          super().apply_user_defaults(tool)
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults     
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Akash\AppData\Local\Temp\pip-build-env-4ug2saqe\overlay\Lib\site-packages\pyqtbuild\builder.py", line 50, in apply_user_defaults     
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

- - please help me resolve this issue.

**Comment by gswwliang** [comment]
Me too, I'm having  the same error now, I'm using python 3.10, here is my information:

Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-install-0s__vj3j/pyqt6_f3f7263ec5f64bf082824a33fb6b0908/project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/0p/9m8lhdwj75172_7t_j59ts_h0000gn/T/pip-build-env-g8ecqxu4/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by sirEgghead** [comment]
I'm in the same boat.  I found several other issues that were closed while referencing #110 , but I didn't find a solution with this.

**Comment by sirEgghead** [comment]
Per #110 , I was able to install it using `pip install pyqt-tools`.  There is a statement regarding less access to custom plugins.  Hopefully this won't turn out to be an issue for me.  Maybe it works for you.

**Comment by Akash47007** [comment]
> Per #110 , I was able to install it using `pip install pyqt-tools`.  There is a statement regarding less access to custom plugins.  Hopefully this won't turn out to be an issue for me.  Maybe it works for you.

I have to install pyqt6-tools, but pip install pyqt-tools will install pyqt5-tools

**Comment by storlak** [comment]
> Per #110 , I was able to install it using `pip install pyqt-tools`. There is a statement regarding less access to custom plugins. Hopefully this won't turn out to be an issue for me. Maybe it works for you.

I am having the same problem actually so what is the difference of pip install **pyqt6**-tools and pip install **pyqt**-tools?

**Comment by storlak** [comment]
Hello i am having the same error when i use `pip install pyqt6-tools`.
Is there any solution offer for this?

**Comment by Akash47007** [comment]
> > Per #110 , I was able to install it using `pip install pyqt-tools`. There is a statement regarding less access to custom plugins. Hopefully this won't turn out to be an issue for me. Maybe it works for you.
> 
> I am having the same problem actually so what is the difference of pip install **pyqt6**-tools and pip install **pyqt**-tools?

pyqt-tools installs pyqt5-tools. But pyqt6-tools installs it for pyqt6

**Comment by AbdelRahmanRahal** [comment]
23/5/2024. Error still persists. To me, it just infinitely stops at the `Preparing metadata (pyproject.toml) ...\` step. Can I perhaps install it some other way?

Edit: Yes, there is! https://build-system.fman.io/qt-designer-download

**Comment by marnold1962** [comment]
i had issues as well with pyqt6-tools, but it works with pip install pyqt-tools.          syntax  ..

**Comment by fenchu** [comment]
A workaround is to use pyside6 -> `pyside6-designer`

**Comment by samratpro** [comment]
https://build-system.fman.io/qt-designer-download

**Comment by Akash47007** [comment]
nothing works for me. pyside6 also does not install

**Comment by samratpro** [comment]
> nothing works for me. pyside6 also does not install

It will work only in windows and mac, (https://build-system.fman.io/qt-designer-download) download and install
if you are linux user you can install with 
`sudo apt-get install pyqt5-dev-tools`
`sudo apt-get install pyqt6-dev-tools`

**Comment by santiagoRamirez3** [comment]
I was using windows, and I had the same error. My solution was to create a virtual environment with python 3.9 using conda, and in this venv pyqt6-tools was installed successfully.

**Comment by altendky** [comment]
in case you have the time to help out, fyi: https://github.com/altendky/pyqt-tools/issues/132

**Comment by ensko** [comment]
After also struggling with this for a bit, I got it working using this one-liner using uv:
```
uv tool install --python 3.9 pyqt6-tools --with setuptools==69.5.1
```
This
- makes sure to use Python 3.9 for this tool (downloading it if necessary)
- creates a new virtual environment with `pyqt6-tools setuptools==69.5.1` installed. Without the right setuptools, I got `ModuleNotFoundError: No module named 'pkg_resources'`
- makes `pyqt6-tools` available on your `PATH`, so that it will execute using that venv

you can now use `pyqt6-tools designer` to start the Qt6 Designer
