### ISSUE TITLE
insatlaion erore i tried 2 3 pc still same issue 

### ISSUE THREAD

**Issue by mypythoncourse4** [altendky/pyqt-tools#127]
(.venv) PS C:\Users\admin\Desktop\pyqt6> pip install pyqt6-tools
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.4.2.3.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: click in c:\users\admin\desktop\pyqt6\.venv\lib\site-packages (from pyqt6-tools) (8.1.7)
Collecting pyqt6==6.4.2 (from pyqt6-tools)
  Using cached PyQt6-6.4.2-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
INFO: pip is looking at multiple versions of pyqt6-tools to determine which version is compatible with other requirements. This could take a while.
Collecting pyqt6-tools
  Using cached pyqt6_tools-6.3.1.3.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: pyqt6==6.3.1 in c:\users\admin\desktop\pyqt6\.venv\lib\site-packages (from pyqt6-tools) (6.3.1)
  Using cached pyqt6_tools-6.1.0.3.2-py3-none-any.whl.metadata (8.3 kB)
Collecting pyqt6==6.1.0 (from pyqt6-tools)
  Using cached PyQt6-6.1.0.tar.gz (946 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "C:\Users\admin\Desktop\pyqt6\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\admin\Desktop\pyqt6\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\Desktop\pyqt6\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\sipbuild\api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\sipbuild\project.py", line 608, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\admin\AppData\Local\Temp\pip-install-0n9be2xb\pyqt6_a16b7125c0e74961b9d5cba707ea0d35\project.py", line 60, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\pyqtbuild\project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-g_jaxhl9\overlay\Lib\site-packages\pyqtbuild\builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(.venv) PS C:\Users\admin\Desktop\pyqt6>

**Comment by fenchu** [comment]
same error on mac m1, python 3.12.4

**Comment by sujit22993** [comment]
Same error, Mac m1, tried with python 3.9 and 3.12 both not working.

**Comment by andrerhenry** [comment]
same

**Comment by altendky** [comment]
in case you have the time to help out, fyi: https://github.com/altendky/pyqt-tools/issues/132
