### ISSUE TITLE
"pyqt5-tools installuic" failed on Win10 because pyuic5.exe can't be found

### ISSUE THREAD

**Issue by yehnan** [altendky/pyqt-tools#77]
My environment: Windows 10 and Python 3.7.9(virtual env named py37qt created by Miniconda).

After installed PyQt5 and pyqt5-tools using pip, the Qt Designer can be successfully launched using the command "pyqt5-tools designer".

Then I tried the command "pyqt5-tools installuic", it failed with the following error message.
It seems the command tried to copy the file 'c:\\miniconda3\\envs\\py37qt\\pyuic5.exe', however,
that file exists in 'C:\Miniconda3\envs\py37qt\Scripts'.

(py37qt) R:\>pyqt5-tools installuic
Traceback (most recent call last):
  File "c:\miniconda3\envs\py37qt\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\miniconda3\envs\py37qt\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Miniconda3\envs\py37qt\Scripts\pyqt5-tools.exe\__main__.py", line 7, in <module>
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\miniconda3\envs\py37qt\lib\site-packages\pyqt5_tools\entrypoints.py", line 64, in installuic
    dst=str(destination/maybe_extension('uic')),
  File "c:\miniconda3\envs\py37qt\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\miniconda3\envs\py37qt\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\miniconda3\\envs\\py37qt\\pyuic5.exe'

**Comment by yehnan** [comment]
Excuse me for open the same issue twice.

**Comment by altendky** [comment]
In case anyone ends up here...  #78 is the duplicate where we are working on this.
