### ISSUE TITLE
PyQt5 Fails to install via pip on Raspberry PI OS

### ISSUE THREAD

**Issue by cdeeran** [altendky/pyqt-tools#96]
When I run the following command ```python3 -m pip install PyQt5``` I receive the following error. This happens for all PyQt5 versions known.
```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQt5
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpirebk_zb
         cwd: /tmp/pip-install-o24zj303/pyqt5_c20bb6ee5bf44d86a68c6a77392d5ee8
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 131, in prepare_metadata_for_build_wheel
        config_settings)
      File "/home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-6fbwxio_/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
        "specify a working qmake or add it to PATH")
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /usr/bin/python3 /home/pi/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpirebk_zb Check the logs for full command output.
```

# OS Version
```
Raspberry Pi reference 2021-05-07
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, dcfd74d7d1fa293065ac6d565711e9ff891fe2b8, stage5
```

# Python Version 
Python 3.7.3 (default version on Raspberry Pi). I am also seeing the same error on Python 3.8.x 

# Relative Package Versions
PACKAGE | VERSION
---------|--------
pip | 21.1.2
wheel | 0.36.2
sip | 6.1.0
setuptools | 57.0.0

**Comment by cdeeran** [comment]
It seems I was missing qmake. I have now installed qmake

qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/arm-linux-gnueabihf

However, now the installation just gets stuck preparing wheel meta data

python3 -m pip install PyQt5
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting PyQt5
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... /^canceled
ERROR: Operation cancelled by user

**Comment by altendky** [comment]
This sounds like just a PyQt issue, not pyqt-tools.  See https://github.com/piwheels/packages/issues/3 for my efforts to get PyQt built for PiWheels.

**Comment by cdeeran** [comment]
> This sounds like just a PyQt issue, not pyqt-tools. See [piwheels/packages#3](https://github.com/piwheels/packages/issues/3) for my efforts to get PyQt built for PiWheels.

Sorry, I thought I filed this under PyQt. I will take a look at your link. Thank you!

**Comment by altendky** [comment]
I think that closing this would actually be appropriate?
