### ISSUE TITLE
Attribute Error: type object 'Qt' has no attribute 'AlignHCenter'

### ISSUE THREAD

**Issue by InCogNiTo124** [altendky/pyqt-tools#99]
Using the designer, I have obtained the next .ui file:

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>800</width>
    <height>600</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <widget class="QWidget" name="verticalLayoutWidget">
    <property name="geometry">
     <rect>
      <x>0</x>
      <y>0</y>
      <width>801</width>
      <height>601</height>
     </rect>
    </property>
    <layout class="QVBoxLayout" name="verticalLayout">
     <item alignment="Qt::AlignHCenter">
      <widget class="QLabel" name="label">
       <property name="text">
        <string>OK</string>
       </property>
      </widget>
     </item>
    </layout>
   </widget>
  </widget>
 </widget>
 <resources/>
 <connections/>
</ui>
```

My main.py looks like:
```
from PyQt6 import QtWidgets, uic
import sys

class Ui(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        uic.loadUi('untitled.ui', self)
        self.show()
        return

app = QtWidgets.QApplication(sys.argv)
window = Ui()
sys.exit(app.exec())
```

and the error is:
```
Traceback (most recent call last):
  File "/home/msmetko/Projects/qt/main.py", line 12, in <module>
    window = Ui()
    ...
    ...
  File "/home/msmetko/Projects/qt/venv/lib/python3.9/site-packages/PyQt6/uic/uiparser.py", line 62, in _parse_alignment
    align = getattr(QtCore.Qt, qt_align)
AttributeError: type object 'Qt' has no attribute 'AlignHCenter'
```

It seems that the qt6 designer is not aware that the AlignHCenter was refactored to another module

**Comment by altendky** [comment]
Odds are that won't get fixed here, sorry.  This is just a repackaging of the existing Qt-provided binaries.  Probably best to checkin on the PyQt maillist.  https://www.riverbankcomputing.com/mailman/listinfo/pyqt

**Comment by InCogNiTo124** [comment]
Cool, thanks for the fast reply and the pointer!
